name: Web app unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        working-directory: ./spacebucket-web
      - run: npm run build --if-present
        working-directory: ./spacebucket-web
      - run: npm test
        working-directory: ./spacebucket-web
        env:
          CI: true
